{% set name = "thinc" %}
{% set version = "7.0.2" %}
{% set sha256sum = "e021f316c33f4410586fc600c1b62749c5c4b5677cda03a9c3a63e7ba9cd36f3" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}
  patches:
    - patches/0001-Fix-tests-for-numpy-1.14.0.patch


build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [not x86_64]

requirements:
  build:
    - pip
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - msinttypes  # [win and py27]
    - numpy
    - python
    - setuptools
    - wheel >=0.32.0,<0.33.0

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - murmurhash >=0.28.0,<1.1.0
    - cymem >=2.0.2,<3.0.0
    - preshed >=2.0.1,<3.0.0
    - tqdm >=4.10.0,<5.0.0
    - cytoolz >=0.9.0,<0.10
    - plac >=0.9.6,<1.0.0
    - six >=1.10.0,<2.0.0
    - wrapt >=1.10.0,<1.11.0
    - dill >=0.2.7,<0.3.0
    - pathlib >=1.0.0,<2.0.0  # [py27]
    - msgpack-numpy <0.4.4.0
    - msgpack-python >=0.5.6,<1.0.0

test:
  requires:
    - hypothesis
    - pytest
    - mock

  imports:
    - thinc
    - thinc.api
    - thinc.linear
    - thinc.extra
    - thinc.neural

about:
  home: https://github.com/explosion/thinc/
  license: MIT
  license_file: LICENSE
  summary: 'thinc: Learn super-sparse multi-class models'
  description: |
    thinc is a Cython library for learning models with millions of parameters
    and dozens of classes. It drives https://spacy.io , a pipeline of very
    efficient NLP components. I’ve only used thinc from Cython; no real Python
    API is currently available.

extra:
  recipe-maintainers:
    - rmax
    - honnibal
    - ines
