{% set name = "thinc" %}
{% set version = "6.10.3" %}
{% set sha256sum = "6e89d60f6165685837ebaff6a978ea9ca2b6c8c551a0886125c27de42e8fcf04" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}
  #patches:
  #  - patches/0001-Fix-tests-for-numpy-1.14.0.patch


build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [not x86_64]
  features:
    - vc9   # [win and py27]
    - vc14  # [win and py>=35]

requirements:
  build:
    - toolchain   # [unix]
    - msinttypes  # [win and py27]
    - python
    - setuptools
    # Pin numpy at build time with the minimum version available.
    - numpy 1.8.*   # [not (win and (py35 or py36))]
    - numpy 1.9.*   # [win and py35]
    - numpy 1.11.*  # [win and py36]

  run:
    - python
    - numpy >=1.7
    - numpy >=1.8   # [not (win and (py35 or py36))]
    - numpy >=1.9   # [win and py35]
    - numpy >=1.11  # [win and py36]
    - murmurhash >=0.28,<0.30
    - cymem >=1.30,<1.32
    - preshed >=1.0.0,<2.0.0
    - tqdm >=4.10.0,<5.0.0
    - cytoolz >=0.8,<0.9
    - plac >=0.9.6,<1.0.0
    - six >=1.10.0,<2.0.0
    - wrapt >=1.10.10,<2.0.0
    - dill >=0.2.6,<0.3.0
    - pathlib ==1.0.1  # [py27]
    - msgpack-numpy >=0.4.1,<1.0.0
    # This is correct: The package didn't change name on conda
    - msgpack-python >=0.5.6,<1.0.0

test:
  requires:
    - hypothesis
    - pytest
    - mock

  imports:
    - thinc
    - thinc.api
    - thinc.linear
    - thinc.extra
    - thinc.neural

about:
  home: https://github.com/explosion/thinc/
  license: MIT
  license_file: LICENSE
  summary: 'thinc: Learn super-sparse multi-class models'
  description: |
    thinc is a Cython library for learning models with millions of parameters
    and dozens of classes. It drives https://spacy.io , a pipeline of very
    efficient NLP components. I’ve only used thinc from Cython; no real Python
    API is currently available.

extra:
  recipe-maintainers:
    - rmax
