{% set version = "7.4.1" %}

package:
  name: thinc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/thinc/thinc-{{ version }}.tar.gz
  sha256: 0139fa84dc9b8d88af15e648fc4ae13d899b8b5e49cb26a8f4a0604ee9ad8a9e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win and py27]

requirements:
  build:
    - pip
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy 1.16.*
    - wheel >=0.32.0

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - murmurhash >=0.28.0,<1.1.0
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - cython-blis >=0.4.0,<0.5.0
    - srsly >=0.0.6,<1.1.0
    - wasabi >=0.0.9,<1.1.0
    - plac >=0.9.6,<1.2.0
    - tqdm >=4.10.0,<5.0.0
    - catalogue >=0.0.7,<1.1.0
    - pathlib >=1.0.0,<2.0.0  # [py27]

test:
  requires:
    - hypothesis <=5.0.0
    - pytest
    - mock
  imports:
    - thinc
    - thinc.api
    - thinc.linear
    - thinc.extra
    - thinc.neural

  commands:
    - python -m pytest --tb=native --pyargs thinc

about:
  home: https://github.com/explosion/thinc/
  license: MIT
  license_file: LICENSE
  summary: 'thinc: Learn super-sparse multi-class models'
  description: |
    thinc is a Cython library for learning models with millions of parameters
    and dozens of classes. It drives https://spacy.io , a pipeline of very
    efficient NLP components. I’ve only used thinc from Cython; no real Python
    API is currently available.

extra:
  recipe-maintainers:
    - rmax
    - honnibal
    - ines
    - adrianeboyd
