{% set name = "thinc" %}
{% set version = "6.10.0" %}
{% set sha256sum = "8615dffa31409d2fac85d4806674d914a554aac297f867a03e6dcd84cb6cc99a" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [not x86_64]
  features:
    - vc9   # [win and py27]
    - vc14  # [win and py>=35]

requirements:
  build:
    - toolchain   # [unix]
    - msinttypes  # [win and py27]
    - python
    - setuptools
    - numpy >=1.7

  run:
    - python
    - numpy >=1.7
    - murmurhash >=0.26,<0.27
    - cymem >=1.30,<1.32
    - preshed >=1.0.0,<2.0.0
    - tqdm >=4.10.0,<5.0.0
    - cytoolz >=0.8,<0.9
    - plac >=0.9.6,<1.0.0
    - six >=1.10.0,<2.0.0
    - wrapt
    - dill
    - termcolor
    - pathlib >=1.0.0,<2.0.0  # [py27]

test:
  requires:
    - hypothesis
    - pytest
    - mock

  imports:
    - thinc
    - thinc.api
    - thinc.linear
    - thinc.extra
    - thinc.neural

about:
  home: https://github.com/explosion/thinc/
  license: MIT
  license_file: LICENSE
  summary: 'thinc: Learn super-sparse multi-class models'
  description: |
    thinc is a Cython library for learning models with millions of parameters
    and dozens of classes. It drives https://spacy.io , a pipeline of very
    efficient NLP components. I’ve only used thinc from Cython; no real Python
    API is currently available.

extra:
  recipe-maintainers:
    - rmax
