{% set name = "thinc" %}
{% set version = "6.10.3" %}
{% set sha256sum = "6e89d60f6165685837ebaff6a978ea9ca2b6c8c551a0886125c27de42e8fcf04" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}
  patches:
    - patches/0001-Fix-tests-for-numpy-1.14.0.patch


build:
  number: 3
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [not x86_64]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - msinttypes  # [win and py27]
    - python
    - setuptools
    # Pin numpy at build time with the minimum version available.
    - numpy         # [not (win and (py35 or py36))]
    - numpy         # [win and py35]
    - numpy         # [win and py36]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('numpy') }}    # [not (win and (py35 or py36))]
    - {{ pin_compatible('numpy') }}    # [win and py35]
    - {{ pin_compatible('numpy') }}   # [win and py36]
    - murmurhash >=0.28,<0.30
    - cymem >=1.30,<1.32
    - preshed >=1.0.0,<2.0.0
    - tqdm >=4.10.0,<5.0.0
    - cytoolz >=0.9,<0.10
    - plac >=0.9.6,<1.0.0
    - six >=1.10.0,<2.0.0
    - wrapt >=1.10.10,<2.0.0
    - dill >=0.2.6,<0.3.0
    - termcolor >=1.1.0,<1.2.0
    - pathlib >=1.0.0,<2.0.0  # [py27]
    - msgpack-numpy 
    - msgpack-python >=0.5.0,<0.6.0

test:
  requires:
    - hypothesis
    - pytest
    - mock

  imports:
    - thinc
    - thinc.api
    - thinc.linear
    - thinc.extra
    - thinc.neural

about:
  home: https://github.com/explosion/thinc/
  license: MIT
  license_file: LICENSE
  summary: 'thinc: Learn super-sparse multi-class models'
  description: |
    thinc is a Cython library for learning models with millions of parameters
    and dozens of classes. It drives https://spacy.io , a pipeline of very
    efficient NLP components. I’ve only used thinc from Cython; no real Python
    API is currently available.

extra:
  recipe-maintainers:
    - rmax
    - honnibal
    - ines
