{% set version = "8.3.10" %}

package:
  name: thinc
  version: {{ version }}

source:
  url: https://github.com/explosion/thinc/archive/refs/tags/release-v{{ version }}.tar.gz
  sha256: a00bda30085b72451151835e3415b6b5d071ea74c2ab68dfa8c55f1a0edf2b53

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  # missing cython-blis for ppc
  skip: true  # [ppc64le]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - python
    - pip
    - numpy
    - setuptools
    - wheel
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - murmurhash >=1.0.2,<1.1.0
    - cython-blis >=1.3.0,<1.4.0
  run:
    - python
    - murmurhash >=1.0.2,<1.1.0
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - cython-blis >=1.3.0,<1.4.0
    - wasabi >=0.8.1,<1.2.0
    - srsly >=2.4.0,<3.0.0
    - catalogue >=2.0.4,<2.1.0
    - confection >=0.0.1,<1.0.0
    - pydantic >=2.0.0,<3.0.0
    - packaging >=20.0

test:
  requires:
    - pip
    - hypothesis
    - pytest
    - mock
    - pathy >=0.3.5
  imports:
    - thinc
    - thinc.api
    - thinc.extra
  commands:
    # some pydantic errors during collection in that module
    - rm -f $SP_DIR/thinc/tests/test_config.py  # [py==314 and unix]
    - del %SP_DIR%\thinc\tests\test_config.py   # [py==314 and win]
    - python -m pytest --tb=native --pyargs thinc  # [not ppc64le]
    - pip check

about:
  home: https://github.com/explosion/thinc/
  license: MIT
  license_file: LICENSE
  summary: 'thinc: a lightweight deep learning library'
  description: |
    A refreshing functional take on deep learning, compatible with your
    favorite libraries

extra:
  recipe-maintainers:
    - rmax
    - h-vetinari
    - conda-forge/spacy
