{% set version = "8.3.2" %}

package:
  name: thinc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/thinc/thinc-{{ version }}.tar.gz
  sha256: 3e8ef69eac89a601e11d47fc9e43d26ffe7ef682dcf667c94ff35ff690549aeb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3.0                            # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - cython <3.0
    - python
    - pip
    - numpy
    - setuptools
    - wheel
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - murmurhash >=1.0.2,<1.1.0
    - cython-blis >=0.7.8,<0.8.0
  run:
    - python
    - murmurhash >=1.0.2,<1.1.0
    - cymem >=2.0.2,<2.1.0
    - preshed >=3.0.2,<3.1.0
    - cython-blis >=0.7.8,<0.8.0
    - wasabi >=0.8.1,<1.2.0
    - srsly >=2.4.0,<3.0.0
    - catalogue >=2.0.4,<2.1.0
    - confection >=0.0.1,<1.0.0
    - pydantic >=1.7.4,!=1.8,!=1.8.1,<3.0.0
    - packaging >=20.0
    - typing_extensions >=3.7.4.1,<5.0.0

test:
  requires:
    - hypothesis
    - pytest <8
    - mock
    - pathy >=0.3.5
  imports:
    - thinc
    - thinc.api
    - thinc.extra

  commands:
    {% set tests_to_skip = "_not_a_real_test" %}
    # spurious failure on pypy
    {% set tests_to_skip = tests_to_skip + " or test_initializer_func_setup" %}     # [python_impl == "pypy"]
    - python -m pytest --tb=native --pyargs thinc -k "not ({{ tests_to_skip }})"

about:
  home: https://github.com/explosion/thinc/
  license: MIT
  license_file: LICENSE
  summary: 'thinc: a lightweight deep learning library'
  description: |
    A refreshing functional take on deep learning, compatible with your
    favorite libraries

extra:
  recipe-maintainers:
    - rmax
    - honnibal
    - ines
    - adrianeboyd
