appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: oZcy/AqPiM8jOKzwzjdd4sw2TXliNarhP3BMBtGuE9Ss5a1KU3XXk54akkEwYbPzGbRy2Oac8e0a/Kq0znahSx0stzp+7taSfqiLsEgYkXcMEQ7239dgunvqVvfK8ZJUdf6bYUOzwWGAPWcQJS2gbsztfrlMhZRog8iXZrztJ8qY9/ANxoSQACxZmNjehKGUPkgCsB/D81+I8oRxOuPLQkJv+Ia+h3geIqAv+MFfPwd7RdqvQzB7ZZWhSMecPKjQ5798SrMVWbShnysWbq0D+SIRYhhZHDr1teEyl/Jq2Z/r0OxZ5E7Peq2kJh7YgxGQ9/PRPT3F4S4Ml0/WBnA+ZlDrfJsOOR5EIf6kakZG6w78gpnZWHZsadWZY1qfjjle+5wizJX7H74a8dj8j25gacQN7542YjSoHY5BQZat1/Ke57iMCO5wzA4A+ZTBrEy1IDQpPVBStrpDtWwyhGSulWqXsLUyH2q2Y7NmJ4G3x1ecR4qqdZrUgyAYgZMTZBkfImF6yZIDQ1qRAdV6JKhoGlpI2ZlhVdG8CyfVK5i3l3Giyn81rMTbE/nskqb8UYO420N+eUBCOuEVHhtcp50yHjqBcd/LHqm3caslOgjQ9pv5hwb6S2M7LHSAdg5vfJQeg+Fw630bNPh5/g0jpBkVwApgki1hHCm8wX9njpWpyLQ=}
provider:
  win: azure
conda_forge_output_validation: true
